lint:
  nextflow_config:
    - config_defaults:
        - params.bamtools_filter_se_config
        - params.bamtools_filter_pe_config
nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: Patel H, Langer B, Espinosa-Carrasco J, Syme R
  description: ATACSeq peak-calling and differential analysis pipeline.
  force: false
  is_nfcore: true
  name: atacseq
  org: nf-core
  outdir: .
  version: 2.2.0dev
